module.exports = [
  {
    id: "life-001",
    name: "LIC Jeevan Umang",
    provider: "LIC India",
    type: "life",
    premiumPerMonth: 3500,
    coverageAmount: 2500000,
    features: ["Whole life cover", "Annual survival benefits", "Tax benefits"],
  },
  {
    id: "life-002",
    name: "HDFC Life Click 2 Protect Super",
    provider: "HDFC Life",
    type: "life",
    premiumPerMonth: 2200,
    coverageAmount: 5000000,
    features: ["Term insurance", "Critical illness rider", "Accidental death benefit"],
  },
  {
    id: "life-003",
    name: "Max Life Smart Secure Plus",
    provider: "Max Life",
    type: "life",
    premiumPerMonth: 2800,
    coverageAmount: 7500000,
    features: ["Flexible payout options", "Waiver of premium", "Terminal illness cover"],
  },
  {
    id: "health-001",
    name: "Star Health Family Optima",
    provider: "Star Health",
    type: "health",
    premiumPerMonth: 1800,
    coverageAmount: 1000000,
    features: ["Family floater", "Day care procedures", "Pre and post hospitalization"],
  },
  {
    id: "health-002",
    name: "Niva Bupa ReAssure 2.0",
    provider: "Niva Bupa",
    type: "health",
    premiumPerMonth: 2100,
    coverageAmount: 1500000,
    features: ["Unlimited restore benefit", "Cashless hospitalization", "Annual health check-up"],
  },
  {
    id: "health-003",
    name: "Care Supreme Health Insurance",
    provider: "Care Health",
    type: "health",
    premiumPerMonth: 2400,
    coverageAmount: 2000000,
    features: ["No claim bonus", "OPD add-on", "Automatic recharge benefit"],
  },
  {
    id: "vehicle-001",
    name: "ICICI Lombard Complete Car Protect",
    provider: "ICICI Lombard",
    type: "vehicle",
    premiumPerMonth: 1200,
    coverageAmount: 800000,
    features: ["Zero depreciation", "Roadside assistance", "Engine protection"],
  },
  {
    id: "vehicle-002",
    name: "Bajaj Allianz Drive Smart",
    provider: "Bajaj Allianz",
    type: "vehicle",
    premiumPerMonth: 950,
    coverageAmount: 600000,
    features: ["Cashless garages", "24x7 claim support", "Consumables cover"],
  },
  {
    id: "vehicle-003",
    name: "ACKO Comprehensive Bike Cover",
    provider: "ACKO",
    type: "vehicle",
    premiumPerMonth: 550,
    coverageAmount: 150000,
    features: ["Digital claims", "Personal accident cover", "Theft protection"],
  },
];
