module.exports = [
  {
    id: "mf-001",
    name: "SBI Bluechip Fund",
    category: "Large Cap",
    riskLevel: "medium",
    oneYearReturn: 18.4,
    nav: 78.52,
    minSIP: 500,
  },
  {
    id: "mf-002",
    name: "HDFC Top 100 Fund",
    category: "Large Cap",
    riskLevel: "medium",
    oneYearReturn: 16.9,
    nav: 912.35,
    minSIP: 500,
  },
  {
    id: "mf-003",
    name: "ICICI Prudential Bluechip Fund",
    category: "Large Cap",
    riskLevel: "medium",
    oneYearReturn: 17.8,
    nav: 101.24,
    minSIP: 100,
  },
  {
    id: "mf-004",
    name: "Kotak Emerging Equity Fund",
    category: "Mid Cap",
    riskLevel: "high",
    oneYearReturn: 24.1,
    nav: 82.14,
    minSIP: 500,
  },
  {
    id: "mf-005",
    name: "Nippon India Growth Fund",
    category: "Mid Cap",
    riskLevel: "high",
    oneYearReturn: 26.3,
    nav: 3421.67,
    minSIP: 100,
  },
  {
    id: "mf-006",
    name: "Axis Midcap Fund",
    category: "Mid Cap",
    riskLevel: "high",
    oneYearReturn: 21.7,
    nav: 89.41,
    minSIP: 500,
  },
  {
    id: "mf-007",
    name: "Mirae Asset Tax Saver Fund",
    category: "ELSS",
    riskLevel: "high",
    oneYearReturn: 19.6,
    nav: 39.76,
    minSIP: 500,
  },
  {
    id: "mf-008",
    name: "Canara Robeco ELSS Tax Saver",
    category: "ELSS",
    riskLevel: "medium",
    oneYearReturn: 20.8,
    nav: 153.84,
    minSIP: 500,
  },
  {
    id: "mf-009",
    name: "HDFC Short Term Debt Fund",
    category: "Debt",
    riskLevel: "low",
    oneYearReturn: 7.1,
    nav: 29.33,
    minSIP: 1000,
  },
  {
    id: "mf-010",
    name: "ICICI Prudential Corporate Bond Fund",
    category: "Debt",
    riskLevel: "low",
    oneYearReturn: 7.6,
    nav: 44.92,
    minSIP: 100,
  },
];
